version: "3.3"
services:
  magento:
    image: docker.pentagrama.net.br/bni/magento:1.2.3
    container_name: magento
    entrypoint:
      - /bin/sh
      - -c
      - /usr/local/bin/entrypoint.sh
    command:
      - /usr/bin/supervisord
    working_dir: /var/www/html
    env_file: .env
    volumes:
      - bnimagento_logs:/var/www/html/var/log
      - bnimagento_media:/var/www/html/media
      - bnimagento_report:/var/www/html/var/report
      - ./config/local.xml:/var/www/html/app/etc/local.xml
    networks:
      - infra
      - internal
    restart: "unless-stopped"
    logging:
        driver: "json-file"
        options:
            max-size: "10M"
            max-file: "5"
  redis:
    image: valkey/valkey:8.0.3-alpine3.21
    container_name: magento-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - internal
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "10M"
            max-file: "5"

volumes:
  bnimagento_logs:
    external: true
  bnimagento_media:
    external: true
  bnimagento_report:
    external: true

networks:
  infra:
    external: true
    name: infra
  internal:
